# .scrutinizer.yml
imports:
    - php

tools:
    external_code_coverage: false
    php_changetracking: true
    php_mess_detector: true
    php_pdepend: true
    php_sim: true
    php_analyzer: true
    php_code_sniffer: true

checks:
    php:
        code_rating: true
        duplication: true